### PR TITLE
Remove unneeded newlines from templates' ends

### PR DESCRIPTION
**Pull request by zeppelin**

### CODE REVIEW

**Comment by ryanflorence** [comment]
Thanks for the PR @zeppelin, but I'm closing because I intentionally add the newline:
- Some tools don't like files ending w/o a newline and kind of screw up
- cat file1.js file2.js > concat.js looks much better with new lines

etc. etc.

http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline

**Comment by zeppelin** [comment]
Actually, there is an _extra_ newline at the end of files. There were 2, I removed 1.
Have you intentionally meant 2 newlines?

> Some tools don't like files ending w/o a newline and kind of screw up

This, I guess is covered by 1 newline just fine.

> cat file1.js file2.js > concat.js looks much better with new lines

Is this a common use cases for Ember source files?

**Comment by ryanflorence** [comment]
When I'm at a computer again I'll double check, some silly text editors pretend there is a new line when there isn't, therefore doubling up when there is.

I think `cat` is always a use case, or grunt-concat, or broccoli concat, or or or :P

**Comment by zeppelin** [comment]
So the intention was to have exactly 1 newline?

**Comment by ryanflorence** [comment]
Actually, just checked on my phone, you can see there is no longer a newline in your changes. I'm guessing your text editor is being "smart"

**Comment by ryanflorence** [comment]
Yes, one line.
This has been a convention in programming for a long time.

**Comment by zeppelin** [comment]
If the goal is one line, then we're on the very same page. This was precisely why I raised my eyebrows on closing the PR and still insisting on taking a second look.

Nonetheless, the facts are:

newlines

**Pull request closed without merging**
