### PR TITLE
Add test template generation.

### PR DESCRIPTION
**Pull request by rwjblue**
This is not quite finished, but I figured I'd might as well get a PR going to get some feedback.

When we are ready to merge I can just squash everything down, but for now it is easier to pick through the commits if they are smaller.

The main issue that I have is how to get the module path of the object under test. In `ember-tools` this was provided by the `{{modulePath}}` variable (see [here](https://github.com/rpflorence/ember-tools/blob/tests/src/templates/generate/tests/controller.test.js.hbs#L1)), but with `loom` it is a bit more generalized. Suggestions?

### CODE REVIEW

**Comment by rwjblue** [comment]
All commits squashed.

**Comment by rwjblue** [comment]
I just realized that I wrote the tests in ES6 format ("import User from 'appkit/controllers/user_controller'") instead of using RequireJS/Almond. 

If we get the Almond support merged into EAK then I'd say let's just go that direction. In that case it would support both scenarios (ES6 or RequireJS) perfectly well. 

What is the official party line here?

**Comment by ryanflorence** [comment]
ES6

**Comment by rwjblue** [comment]
OK, this is using ES6 syntax.  What do you think?  Any major changes before you see this being merged in?

**Pull request closed without merging**
